### PR TITLE
Fixes #124: Avoid duplication of names of proxy classes based on the same class

### LINKED ISSUE #124: When using ProxyBuilder#withSharedClassLoader(), the proxy classes for the same class will be the same even though different interfaces are specified by implementing()
- dexmaker 2.19.1

```java
public class ProxyBuilderTest {

    @Test
    public void test() throws IOException {
        Class<?> c1 = ProxyBuilder.forClass(C.class)
                                  .implementing(I1.class)
                                  .withSharedClassLoader()
                                  .buildProxyClass();
        Class<?> c2 = ProxyBuilder.forClass(C.class)
                                  .implementing(I2.class)
                                  .withSharedClassLoader()
                                  .buildProxyClass();
        assertNotSame(c1, c2); // java.lang.AssertionError: expected not same
    }

    static class C {
    }

    interface I1 {
    }

    interface I2 {
    }

}
```

### PR DESCRIPTION
**Pull request by tmurakami**
Fixes #124
- Add the hash of interfaces to the proxy class name
- Include interfaces in the proxy class cache key

### CODE REVIEW

File: dexmaker-tests/src/androidTest/java/com/android/dx/stock/ProxyBuilderTest.java [hunk 1]
```diff
@@ -1239,4 +1243,34 @@ public Object invoke(Object proxy, Method method, Object[] args) throws Throwabl
...
+        proxyFor(SimpleClass.class).implementing(Callable.class).buildProxyClass();
+        assertEquals(2, getGeneratedProxyClasses().size());
+        assertEquals(3, versionedDxDir.listFiles().length);
+
+        Map<?, ?> cacheCopy = new HashMap<>(getGeneratedProxyClasses());
+        Set<?> generatedFiles = new HashSet<>(Arrays.asList(versionedDxDir.listFiles()));
+
+        proxyFor(SimpleClass.class).implementing(Runnable.class).buildProxyClass();
+        proxyFor(SimpleClass.class).implementing(Callable.class).buildProxyClass();
+        assertEquals(cacheCopy, getGeneratedProxyClasses());
```
Comment (moltmann) [inline dexmaker-tests/src/androidTest/java/com/android/dx/stock/ProxyBuilderTest.java]: Should't we check that the proxy classes are not the same?

File: dexmaker-tests/src/androidTest/java/com/android/dx/stock/ProxyBuilderTest.java [hunk 2]
```diff
@@ -1239,4 +1243,34 @@ public Object invoke(Object proxy, Method method, Object[] args) throws Throwabl
...
+                .implementing(Runnable.class).withSharedClassLoader().buildProxyClass();
+        Class<?> c2 = ProxyBuilder.forClass(SimpleClass.class)
+                .implementing(Callable.class).withSharedClassLoader().buildProxyClass();
+        assertNotSame(c1, c2);
+    }
+
+    @Test
+    public void testImplementingDifferentInterfacesWithDexMakerCaching() throws Exception {
+        proxyFor(SimpleClass.class).implementing(Runnable.class).buildProxyClass();
+        assertEquals(1, getGeneratedProxyClasses().size());
```
Comment (moltmann) [inline dexmaker-tests/src/androidTest/java/com/android/dx/stock/ProxyBuilderTest.java]: Why do we care how the cache is internally organized?

File: dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java [hunk 3]
```diff
@@ -41,7 +41,6 @@
 import java.util.HashSet;
```
Comment (moltmann) [inline dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java]: I think you still have to change the implementation of Dexmaker#generateFileName to also consider the interfaces

File: dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java [hunk 4]
```diff
@@ -813,8 +811,9 @@ private void getMethodsToProxy(Set<MethodSetEntry> sink, Set<MethodSetEntry> see
         }
     }
 
-    private static <T> String getMethodNameForProxyOf(Class<T> clazz) {
-        return clazz.getName().replace(".", "/") + "_Proxy";
+    private static <T> String getMethodNameForProxyOf(Class<T> clazz, Set<Class<?>> interfaces) {
+        String interfacesHash = Integer.toHexString(interfaces.hashCode());
+        return clazz.getName().replace(".", "/") + "_" + interfacesHash + "_Proxy";
```
Comment (moltmann) [inline dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java]: Why is this necessary? You already added the interfaces to the proxy-key

File: dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java [hunk 5]
```diff
@@ -949,6 +944,8 @@ public int hashCode() {
     private static class ProxiedClass<U> {
         final Class<U> clazz;
 
+        final Set<?> interfaces;
```
Comment (moltmann) [inline dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java]: Does interface order matter for default inheritance with default methods?

File: dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java (hunk 4 above)
Comment (tmurakami) [reply dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java]: In the original implementation, since the proxy classes based on the same class would have the same name, the code below would always return the first generated class.

https://github.com/linkedin/dexmaker/blob/ab6d870302154e502a693337944d550a31cbb2f6/dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java#L335

File: dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java (hunk 3 above)
Comment (tmurakami) [reply dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java]: I'm not sure why we should do that to solve #124. Could you please explain the reason?

File: dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java (hunk 4 above)
Comment (moltmann) [reply dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java]: makes sense

File: dexmaker-tests/src/androidTest/java/com/android/dx/stock/ProxyBuilderTest.java (hunk 2 above)
Comment (moltmann) [reply dexmaker-tests/src/androidTest/java/com/android/dx/stock/ProxyBuilderTest.java]: I am not against this, but seems an odd thing to check in this test.
We really care that the two classes are different, not which files are generated.

File: dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java (hunk 5 above)
Comment (tmurakami) [reply dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java]: Originally the order of interfaces is not considered.

https://github.com/linkedin/dexmaker/pull/125/files/ab6d870302154e502a693337944d550a31cbb2f6#diff-50d57f6ae81387a5d38ed25e3e7b0dd9L278

I'm not sure if we should consider that order in this PR.

Comment (moltmann) [reply dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java]: Let's do it now to avoid another bug.

File: dexmaker-tests/src/androidTest/java/com/android/dx/stock/ProxyBuilderTest.java (hunk 1 above)
Comment (tmurakami) [reply dexmaker-tests/src/androidTest/java/com/android/dx/stock/ProxyBuilderTest.java]: Deleted a test to check the cache

File: dexmaker-tests/src/androidTest/java/com/android/dx/stock/ProxyBuilderTest.java (hunk 2 above)
Comment (tmurakami) [reply dexmaker-tests/src/androidTest/java/com/android/dx/stock/ProxyBuilderTest.java]: Deleted a test to check the cache

File: dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java (hunk 3 above)
Comment (tmurakami) [reply dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java]: Changed generateFileName() to consider interfaces

File: dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java (hunk 5 above)
Comment (tmurakami) [reply dexmaker/src/main/java/com/android/dx/stock/ProxyBuilder.java]: Changed ProxiedClass to consider interface order

**Comment by moltmann** [comment]
Looks fine to me. @drewhannay what do you think?

**Comment by drewhannay** [comment]
Yep, lgtm. :shipit:
